In [4]:
import pickle
import joblib
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [6]:
#read the data


df = pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\MACHINE_LEARNING-2\housing.csv')

In [7]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [10]:
df.shape

(20640, 10)

In [11]:
df =df.dropna()

In [12]:
x=df.drop(columns='median_house_value')

In [23]:
y =df.median_house_value.copy()

In [24]:
x

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [25]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20433, dtype: float64

In [30]:
print(x.shape)
import pandas as pd

x = pd.get_dummies(x, drop_first=True)

(20433, 9)

Train the model

In [31]:
model =LinearRegression()

In [32]:
model.fit(x,y)

LinearRegression()

In [29]:
print(type(model))
print(type(x))
print(type(y))

<class 'sklearn.linear_model._base.LinearRegression'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [33]:
y_pred =model.predict(x)

In [34]:
y_pred

array([410542.89633527, 419402.23065049, 379874.19142365, ...,
        39303.33119253,  50351.13924994,  67599.02403131])

In [35]:
r2_score(y,y_pred)

0.6464638320299037

### pickle

In [36]:
with open('model.pkl','wb') as f:
    pickle.dump(model,f)

In [ ]:
with open("model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

prediction = loaded_model.predict(X_test)

In [43]:
#joblib

In [37]:
joblib.dump(model,'model.joblib')

['model.joblib']

In [40]:
loaded_model = joblib.load("model.joblib")

prediction = loaded_model.predict(x)

In [41]:
prediction

array([410542.89633527, 419402.23065049, 379874.19142365, ...,
        39303.33119253,  50351.13924994,  67599.02403131])

In [42]:
r2_score(y,prediction)

0.6464638320299037